### PR TITLE
signup screen

### PR DESCRIPTION
**Pull request by fatchat**
link to signup from login and vice-versa

### CODE REVIEW

**Comment by fatchat** [comment]
@mdshamoon i can't seem to display `signupError` on line 105... will ask you when we meet on Monday

**Review by mdshamoon — CHANGES_REQUESTED** [review]
Let's remove all the console log's. Otherwise looks good.

We should also create a common structure for all auth screens and import it in login signup, etc since most of the UI elements are the same. We can target that in a separate PR.

**Comment by fatchat** [comment]
Console logs (.log and .error) removed

**Comment by fatchat** [comment]
@mdshamoon would you merge please

**Pull request merged**
